"""Native finite-volume solver API."""

from source.solvers.FVM import (
    AdaptiveCartesianMesher,
    BoundaryConfig,
    BoxRefinement,
    DynamicMeshConfig,
    ExecutionConfig,
    FieldState,
    ForcesConfig,
    FVMSetup,
    LinearSolverConfig,
    LinearSolveResult,
    MeshConfig,
    OutputSetup,
    PimpleControl,
    RunAcceptancePolicy,
    SchemesConfig,
    Solver,
    StepDiagnostics,
    TimeConfig,
    TransportConfig,
    TurbulenceConfig,
    setup_fvm_solver,
    solver_configs_from_case,
)
from source.solvers.FVM.fields.diagnostics import (
    compute_continuity_error,
    compute_enstrophy,
    compute_kinetic_energy,
)
from source.solvers.FVM.immersed_boundary import ImmersedBody
from source.solvers.FVM.mesh import geometry
from source.solvers.FVM.mesh.gmsh_importer import GmshImporter

__all__ = [
    "AdaptiveCartesianMesher",
    "BoundaryConfig",
    "BoxRefinement",
    "DynamicMeshConfig",
    "ExecutionConfig",
    "FieldState",
    "ForcesConfig",
    "FVMSetup",
    "GmshImporter",
    "ImmersedBody",
    "LinearSolveResult",
    "LinearSolverConfig",
    "MeshConfig",
    "OutputSetup",
    "PimpleControl",
    "RunAcceptancePolicy",
    "SchemesConfig",
    "Solver",
    "StepDiagnostics",
    "TimeConfig",
    "TransportConfig",
    "TurbulenceConfig",
    "compute_continuity_error",
    "compute_enstrophy",
    "compute_kinetic_energy",
    "geometry",
    "setup_fvm_solver",
    "solver_configs_from_case",
]
