"""Vortex-particle and vortex-lattice solvers for OpenONDA."""

from .boundary_elements import vlm
from .boundary_elements.panels.coupling.kinematics import BodyPose
from .boundary_elements.panels.solver.panel_solver import PanelSolver
from .boundary_elements.vlm.config import (
    ForceConfig,
    VLMMeshSetup,
    VLMSetup,
    VLMSurfaceSetup,
)
from .config import (
    AdvectionConfig,
    Backup,
    DiagnosticsConfig,
    DivergenceLimit,
    DivergenceRelaxationConfig,
    FilamentRefinementConfig,
    FiniteStateCheck,
    GrowthLimit,
    HealthError,
    HealthLimits,
    LagrangianCFLLimit,
    MisalignmentLimit,
    Numerics,
    PanelBodySetup,
    ParticleStrengthLimit,
    RestartState,
    RunPlan,
    Samplers,
    StabilizationConfig,
    StretchingConfig,
    TurbulenceConfig,
    VelocityConfig,
    ViscousConfig,
    VPMCase,
)
from .core.solver import VPMSolver
from .diagnostics import FlowIntegralsSampler, RingDiagnosticsSampler
from .initialization import (
    CylindricalDistribution,
    FilamentDisturbance,
    InitialCondition,
    InitialVelocity,
    IsotropicTurbulence,
    NoisyRectangularDistribution,
    ParticleCoreCompensation,
    ParticleDistribution,
    RectangularDistribution,
    TaylorGreenVortex,
    ToroidalDistribution,
    TriangularPrismDistribution,
    VortexDoublet,
    VortexFilament,
    VortexParticleSet,
    VortexRing,
    WidnallDisturbance,
)
from .io.sampling import EverySteps, EveryTime, FinalOnly
from .stabilization import (
    DivergenceRelaxationError,
    FilamentRefinementError,
    StabilizationError,
    StabilizationManager,
)

__all__ = [
    "AdvectionConfig",
    "DivergenceRelaxationConfig",
    "DivergenceRelaxationError",
    "Backup",
    "DivergenceLimit",
    "DiagnosticsConfig",
    "FinalOnly",
    "FilamentRefinementConfig",
    "FilamentRefinementError",
    "FiniteStateCheck",
    "FilamentDisturbance",
    "InitialVelocity",
    "InitialCondition",
    "ForceConfig",
    "FlowIntegralsSampler",
    "IsotropicTurbulence",
    "EverySteps",
    "EveryTime",
    "GrowthLimit",
    "HealthError",
    "HealthLimits",
    "LagrangianCFLLimit",
    "ParticleStrengthLimit",
    "MisalignmentLimit",
    "BodyPose",
    "PanelSolver",
    "PanelBodySetup",
    "Numerics",
    "RestartState",
    "ParticleDistribution",
    "ParticleCoreCompensation",
    "Samplers",
    "RingDiagnosticsSampler",
    "StabilizationConfig",
    "StabilizationError",
    "StabilizationManager",
    "StretchingConfig",
    "TurbulenceConfig",
    "VLMMeshSetup",
    "VLMSetup",
    "VLMSurfaceSetup",
    "RunPlan",
    "VPMCase",
    "VPMSolver",
    "VelocityConfig",
    "ViscousConfig",
    "VortexParticleSet",
    "WidnallDisturbance",
    "CylindricalDistribution",
    "NoisyRectangularDistribution",
    "RectangularDistribution",
    "ToroidalDistribution",
    "TriangularPrismDistribution",
    "TaylorGreenVortex",
    "VortexDoublet",
    "VortexFilament",
    "VortexRing",
    "vlm",
]
