"""The supported solver facades expose one explicit, reviewable API each."""

from __future__ import annotations


def test_public_solver_api_matches_the_explicit_allowlist():
    import openonda.coupler as coupler
    import openonda.fvm as fvm
    import openonda.vpm as vpm

    expected = {
        fvm: {
            "AdaptiveCartesianMesher",
            "BoundaryLayerSpec",
            "BoundaryConfig",
            "BoxRefinement",
            "ComputeConfig",
            "DiscretizationConfig",
            "ExplicitCylinderGridMesher",
            "FieldState",
            "ForceSampler",
            "FVMSetup",
            "FVMSolver",
            "GmshImporter",
            "IBMForceSampler",
            "ImmersedBody",
            "LinearSolveResult",
            "LinearSolverConfig",
            "LineSampler",
            "LoggingConfig",
            "MeshMotionConfig",
            "MeshQualityConfig",
            "OutputConfig",
            "PimpleControl",
            "RunAcceptanceLimits",
            "SamplingSchedule",
            "StepDiagnostics",
            "SurfaceSampler",
            "TimeConfig",
            "TransportConfig",
            "TurbulenceConfig",
            "compute_continuity_error",
            "compute_enstrophy",
            "compute_kinetic_energy",
            "coupling_box_mesh",
            "create_fvm_solver",
            "geometry",
            "periodic_square_mesh",
            "stretched",
            "wall_refined_axis",
        },
        vpm: {
            "AdvectionConfig",
            "Backup",
            "CylindricalDistribution",
            "DiagnosticsConfig",
            "DivergenceLimit",
            "DivergenceRelaxationConfig",
            "DivergenceRelaxationError",
            "EverySteps",
            "EveryTime",
            "FilamentDisturbance",
            "FilamentRefinementConfig",
            "FilamentRefinementError",
            "FinalOnly",
            "FiniteStateCheck",
            "FlowIntegralsSampler",
            "ForceConfig",
            "GrowthLimit",
            "HealthError",
            "HealthLimits",
            "InitialCondition",
            "InitialVelocity",
            "IsotropicTurbulence",
            "LagrangianCFLLimit",
            "LineSampler",
            "ManeuverVLM",
            "MisalignmentLimit",
            "NoisyRectangularDistribution",
            "Numerics",
            "PanelBodySetup",
            "PanelSolver",
            "ParticleCoreCompensation",
            "ParticleDistribution",
            "ParticleStrengthLimit",
            "PitchingVLM",
            "RectangularDistribution",
            "RestartState",
            "RingDiagnosticsSampler",
            "RotatingVLM",
            "RunPlan",
            "Samplers",
            "SmoothRampVLM",
            "StabilizationConfig",
            "StaticVLM",
            "StretchingConfig",
            "SurfaceSampler",
            "TaylorGreenVortex",
            "ToroidalDistribution",
            "TranslatingVLM",
            "TriangularPrismDistribution",
            "TurbulenceConfig",
            "VelocityConfig",
            "ViscousConfig",
            "VLMMeshSetup",
            "VLMSetup",
            "VLMSurfaceSetup",
            "VortexDoublet",
            "VortexFilament",
            "VortexParticleSet",
            "VortexRing",
            "VPMCase",
            "VPMSolver",
            "WidnallDisturbance",
        },
        coupler: {"CouplerSetup", "FVMVPMCoupler", "create_coupler"},
    }

    for module, names in expected.items():
        assert set(module.__all__) == names
        for name in names:
            assert getattr(module, name) is not None
